name: Mirror to Account2

on:
  push:
    branches: ["main"]   # or "master" if your default branch is master
  workflow_dispatch:      # ✅ allows you to run this manually from Actions tab


jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to Account2 repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote add mirror https://x-access-token:${{ secrets.ACCOUNT2_TOKEN }}@github.com/theUser0011/fork-repo.git
          git push mirror main --force
