name: Mirror to Account2

on:
  push:
    branches: ["master"]   # or "main" if that’s your default branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3



      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote remove origin || true
          git remote add mirror https://theUser0011:${{ secrets.ACCOUNT2_PAT }}@github.com/theUser0011/fork-repo.git
          git push mirror master --force

