name: Mirror to Account2

on:
  push:
    branches: ["master"]   # or "main" if that’s your default branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3



      - name: Push to Account2 repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote remove origin
          git remote add mirror https://x-access-token:${{ secrets.ACCOUNT2_TOKEN }}@github.com/theUser0011/fork-repo.git
          git push mirror master --force
